name: Build & Deploy FastAPI

on:
  push:
    branches: ["master"]
    paths:
      - "app_fastapi/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
            | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build image
        run: |
          docker build -t fastapi-app app_fastapi/

      - name: Tag image
        run: |
          docker tag fastapi-app:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/apprepository:latest

      - name: Push image
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/apprepository:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster AppCluster \
            --service AppService \
            --force-new-deployment
